/**
 * This class is generated by jOOQ
 */
package tech.codingclub.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SongdbRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.tables.records.SongdbRecord> implements org.jooq.Record6<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1014293367;

	/**
	 * Setter for <code>public.Songdb.album_name</code>.
	 */
	public void setAlbumName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.Songdb.album_name</code>.
	 */
	public java.lang.String getAlbumName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.Songdb.album_image_link</code>.
	 */
	public void setAlbumImageLink(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.Songdb.album_image_link</code>.
	 */
	public java.lang.String getAlbumImageLink() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.Songdb.cast</code>.
	 */
	public void setCast(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.Songdb.cast</code>.
	 */
	public java.lang.String getCast() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.Songdb.music_composer</code>.
	 */
	public void setMusicComposer(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.Songdb.music_composer</code>.
	 */
	public java.lang.String getMusicComposer() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.Songdb.song_name</code>.
	 */
	public void setSongName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.Songdb.song_name</code>.
	 */
	public java.lang.String getSongName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.Songdb.song_download_link</code>.
	 */
	public void setSongDownloadLink(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.Songdb.song_download_link</code>.
	 */
	public java.lang.String getSongDownloadLink() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return tech.codingclub.tables.Songdb.SONGDB.ALBUM_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return tech.codingclub.tables.Songdb.SONGDB.ALBUM_IMAGE_LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.tables.Songdb.SONGDB.CAST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return tech.codingclub.tables.Songdb.SONGDB.MUSIC_COMPOSER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return tech.codingclub.tables.Songdb.SONGDB.SONG_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return tech.codingclub.tables.Songdb.SONGDB.SONG_DOWNLOAD_LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getAlbumName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAlbumImageLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCast();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getMusicComposer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSongName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSongDownloadLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value1(java.lang.String value) {
		setAlbumName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value2(java.lang.String value) {
		setAlbumImageLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value3(java.lang.String value) {
		setCast(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value4(java.lang.String value) {
		setMusicComposer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value5(java.lang.String value) {
		setSongName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord value6(java.lang.String value) {
		setSongDownloadLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongdbRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SongdbRecord
	 */
	public SongdbRecord() {
		super(tech.codingclub.tables.Songdb.SONGDB);
	}

	/**
	 * Create a detached, initialised SongdbRecord
	 */
	public SongdbRecord(java.lang.String albumName, java.lang.String albumImageLink, java.lang.String cast, java.lang.String musicComposer, java.lang.String songName, java.lang.String songDownloadLink) {
		super(tech.codingclub.tables.Songdb.SONGDB);

		setValue(0, albumName);
		setValue(1, albumImageLink);
		setValue(2, cast);
		setValue(3, musicComposer);
		setValue(4, songName);
		setValue(5, songDownloadLink);
	}
}
